// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type tracingShadow struct {
	Enabled      *bool   `json:"enabled"       toml:"enabled"       yaml:"enabled"`
	OTLPEndpoint *string `json:"otlp_endpoint" toml:"otlp_endpoint" yaml:"otlp_endpoint"`
}

type pProfShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}

type metricsShadow struct {
	Enabled  *bool   `json:"enabled"   toml:"enabled"   yaml:"enabled"`
	IPV4Host *string `json:"ipv4_host" toml:"ipv4_host" yaml:"ipv4_host"`
	IPV6Host *string `json:"ipv6_host" toml:"ipv6_host" yaml:"ipv6_host"`
	Port     *uint16 `json:"port"      toml:"port"      yaml:"port"`
}

type hTTPShadow struct {
	IPV4Host       *string        `json:"ipv4_host"       toml:"ipv4_host"       yaml:"ipv4_host"`
	IPV6Host       *string        `json:"ipv6_host"       toml:"ipv6_host"       yaml:"ipv6_host"`
	Port           *uint16        `json:"port"            toml:"port"            yaml:"port"`
	TrustedProxies *[]string      `json:"trusted_proxies" toml:"trusted_proxies" yaml:"trusted_proxies"`
	CORSHosts      *[]string      `json:"cors_hosts"      toml:"cors_hosts"      yaml:"cors_hosts"`
	Tracing        *tracingShadow `json:"tracing"         toml:"tracing"         yaml:"tracing"`
	PProf          *pProfShadow   `json:"pprof"           toml:"pprof"           yaml:"pprof"`
	Metrics        *metricsShadow `json:"metrics"         toml:"metrics"         yaml:"metrics"`
}

type configShadow struct {
	HTTP *hTTPShadow `json:"http" toml:"http" yaml:"http"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.HTTP.IPV4Host = "0.0.0.0"
	set("http.ipv4_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.IPV6Host = "::"
	set("http.ipv6_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.IPV4Host = "127.0.0.1"
	set("http.metrics.ipv4_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.IPV6Host = "::1"
	set("http.metrics.ipv6_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.Port = uint16(8081)
	set("http.metrics.port", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.HTTP != nil {
		if s.HTTP.IPV4Host != nil {
			cfg.HTTP.IPV4Host = *s.HTTP.IPV4Host
			set("http.ipv4_host", configulator.LayerFile, file)
		}
		if s.HTTP.IPV6Host != nil {
			cfg.HTTP.IPV6Host = *s.HTTP.IPV6Host
			set("http.ipv6_host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted_proxies", configulator.LayerFile, file)
		}
		if s.HTTP.CORSHosts != nil {
			cfg.HTTP.CORSHosts = *s.HTTP.CORSHosts
			set("http.cors_hosts", configulator.LayerFile, file)
		}
		if s.HTTP.Tracing != nil {
			if s.HTTP.Tracing.Enabled != nil {
				cfg.HTTP.Tracing.Enabled = *s.HTTP.Tracing.Enabled
				set("http.tracing.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.Tracing.OTLPEndpoint != nil {
				cfg.HTTP.Tracing.OTLPEndpoint = *s.HTTP.Tracing.OTLPEndpoint
				set("http.tracing.otlp_endpoint", configulator.LayerFile, file)
			}
		}
		if s.HTTP.PProf != nil {
			if s.HTTP.PProf.Enabled != nil {
				cfg.HTTP.PProf.Enabled = *s.HTTP.PProf.Enabled
				set("http.pprof.enabled", configulator.LayerFile, file)
			}
		}
		if s.HTTP.Metrics != nil {
			if s.HTTP.Metrics.Enabled != nil {
				cfg.HTTP.Metrics.Enabled = *s.HTTP.Metrics.Enabled
				set("http.metrics.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.IPV4Host != nil {
				cfg.HTTP.Metrics.IPV4Host = *s.HTTP.Metrics.IPV4Host
				set("http.metrics.ipv4_host", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.IPV6Host != nil {
				cfg.HTTP.Metrics.IPV6Host = *s.HTTP.Metrics.IPV6Host
				set("http.metrics.ipv6_host", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.Port != nil {
				cfg.HTTP.Metrics.Port = *s.HTTP.Metrics.Port
				set("http.metrics.port", configulator.LayerFile, file)
			}
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "ipv4_host"); ok {
		cfg.HTTP.IPV4Host = v
		set("http.ipv4_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "ipv6_host"); ok {
		cfg.HTTP.IPV6Host = v
		set("http.ipv6_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = uint16(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted_proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.TrustedProxies = lst
		set("http.trusted_proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors_hosts"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.CORSHosts = lst
		set("http.cors_hosts", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "tracing", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Tracing.Enabled = p
		set("http.tracing.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "tracing", "otlp_endpoint"); ok {
		cfg.HTTP.Tracing.OTLPEndpoint = v
		set("http.tracing.otlp_endpoint", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.PProf.Enabled = p
		set("http.pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Metrics.Enabled = p
		set("http.metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "ipv4_host"); ok {
		cfg.HTTP.Metrics.IPV4Host = v
		set("http.metrics.ipv4_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "ipv6_host"); ok {
		cfg.HTTP.Metrics.IPV6Host = v
		set("http.metrics.ipv6_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Metrics.Port = uint16(p)
		set("http.metrics.port", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"http" + o.Separator + "ipv4_host",
		"http" + o.Separator + "ipv6_host",
		"http" + o.Separator + "port",
		"http" + o.Separator + "trusted_proxies",
		"http" + o.Separator + "cors_hosts",
		"http" + o.Separator + "tracing" + o.Separator + "enabled",
		"http" + o.Separator + "tracing" + o.Separator + "otlp_endpoint",
		"http" + o.Separator + "pprof" + o.Separator + "enabled",
		"http" + o.Separator + "metrics" + o.Separator + "enabled",
		"http" + o.Separator + "metrics" + o.Separator + "ipv4_host",
		"http" + o.Separator + "metrics" + o.Separator + "ipv6_host",
		"http" + o.Separator + "metrics" + o.Separator + "port",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "0.0.0.0", "The IPv4 address to bind the HTTP server to. 0.0.0.0 is all interfaces")
	fs.String(names[1], "::", "The IPv6 address to bind the HTTP server to. :: is all interfaces")
	fs.Uint16(names[2], 8080, "The port to bind the HTTP server to. IPv4 and IPv6 share it")
	fs.StringSlice(names[3], nil, "IP addresses or CIDR ranges of reverse proxies trusted to set the X-Forwarded-For header")
	fs.StringSlice(names[4], nil, "Origins allowed to open a websocket. An entry may be a bare host (example.com, matching any port), a host:port (example.com:8080) or a full URL (https://example.com). * allows any origin")
	fs.Bool(names[5], false, "Enable OpenTelemetry tracing")
	fs.String(names[6], "", "The OpenTelemetry collector endpoint")
	fs.Bool(names[7], false, "Enable Go pprof")
	fs.Bool(names[8], false, "Enable the Prometheus metrics server")
	fs.String(names[9], "127.0.0.1", "The IPv4 address to bind the Prometheus metrics server to. 127.0.0.1 is localhost")
	fs.String(names[10], "::1", "The IPv6 address to bind the Prometheus metrics server to. ::1 is localhost")
	fs.Uint16(names[11], 8081, "The port to bind the Prometheus metrics server to. IPv4 and IPv6 share it")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "http" + o.Separator + "ipv4_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.ipv4_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.IPV4Host = v
		set("http.ipv4_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "ipv6_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.ipv6_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.IPV6Host = v
		set("http.ipv6_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "trusted_proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted_proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted_proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors_hosts"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors_hosts",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORSHosts = v
		set("http.cors_hosts", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "tracing" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Tracing.Enabled = v
		set("http.tracing.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "tracing" + o.Separator + "otlp_endpoint"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.otlp_endpoint",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Tracing.OTLPEndpoint = v
		set("http.tracing.otlp_endpoint", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.PProf.Enabled = v
		set("http.pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.Enabled = v
		set("http.metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "ipv4_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.ipv4_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.IPV4Host = v
		set("http.metrics.ipv4_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "ipv6_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.ipv6_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.IPV6Host = v
		set("http.metrics.ipv6_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.Port = v
		set("http.metrics.port", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "ipv4_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV4Host = &str
			default:
				return configJSONError(path+".ipv4_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "ipv6_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV6Host = &str
			default:
				return configJSONError(path+".ipv6_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "trusted_proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted_proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted_proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "cors_hosts":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".cors_hosts", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".cors_hosts"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.CORSHosts = &out
			}
		case "tracing":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".tracing", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub tracingShadow
				if err := sub.decodeJSON(dec, path+".tracing"); err != nil {
					return err
				}
				s.Tracing = &sub
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, path+".pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, path+".metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *tracingShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "otlp_endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.OTLPEndpoint = &str
			default:
				return configJSONError(path+".otlp_endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "ipv4_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV4Host = &str
			default:
				return configJSONError(path+".ipv4_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "ipv6_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV6Host = &str
			default:
				return configJSONError(path+".ipv6_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "http.ipv4_host = %v\n", c.HTTP.IPV4Host)
	fmt.Fprintf(&b, "http.ipv6_host = %v\n", c.HTTP.IPV6Host)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "http.trusted_proxies = %v\n", c.HTTP.TrustedProxies)
	fmt.Fprintf(&b, "http.cors_hosts = %v\n", c.HTTP.CORSHosts)
	fmt.Fprintf(&b, "http.tracing.enabled = %v\n", c.HTTP.Tracing.Enabled)
	fmt.Fprintf(&b, "http.tracing.otlp_endpoint = %v\n", c.HTTP.Tracing.OTLPEndpoint)
	fmt.Fprintf(&b, "http.pprof.enabled = %v\n", c.HTTP.PProf.Enabled)
	fmt.Fprintf(&b, "http.metrics.enabled = %v\n", c.HTTP.Metrics.Enabled)
	fmt.Fprintf(&b, "http.metrics.ipv4_host = %v\n", c.HTTP.Metrics.IPV4Host)
	fmt.Fprintf(&b, "http.metrics.ipv6_host = %v\n", c.HTTP.Metrics.IPV6Host)
	fmt.Fprintf(&b, "http.metrics.port = %v\n", c.HTTP.Metrics.Port)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
